### ISSUE TITLE
D_Parser error

### ISSUE THREAD

**Issue by godvin** [aBothe/D-IDE#5]
If source file is empty, i have error when i am editing file:

```
Index was outside the bounds of the array. (mscorlib)

   at System.String.get_Chars(Int32 index)
   at D_Parser.DocumentHelper.GetOffsetByRelativeLocation(String Text, CodeLocation caret, Int32 caretOffset, CodeLocation target) in a:\Projects\D-IDE\Parser\DParser2\Misc\DocumentHelper.cs:line 77
   at D_Parser.Completion.CtrlSpaceCompletionProvider.FindCurrentCaretContext(String code, IBlockNode CurrentScope, Int32 caretOffset, CodeLocation caretLocation, ParserTrackerVariables& TrackerVariables) in a:\Projects\D-IDE\Parser\DParser2\Completion\Providers\CtrlSpaceCompletionProvider.cs:line 235
   at D_Parser.Completion.AbstractCompletionProvider.Create(ICompletionDataGenerator dataGen, IEditorData Editor, String EnteredText) in a:\Projects\D-IDE\Parser\DParser2\Completion\AbstractCompletionProvider.cs:line 31
   at D_Parser.Completion.AbstractCompletionProvider.BuildCompletionData(ICompletionDataGenerator dataGen, IEditorData editor, String EnteredText) in a:\Projects\D-IDE\Parser\DParser2\Completion\AbstractCompletionProvider.cs:line 88
   at D_IDE.D.DCodeCompletionSupport.BuildCompletionData(DEditorDocument EditorDocument, IList`1 l, String EnteredText, String& lastResultPath) in a:\Projects\D-IDE\D-IDE.D\CodeCompletion\DCodeCompletionSupport.cs:line 22
   at D_IDE.D.DEditorDocument.ShowCodeCompletionWindow(String EnteredText) in a:\Projects\D-IDE\D-IDE.D\DEditor\DEditorDocument.cs:line 1100
```

 Error gone if i put empty line at end of file. Possibility need remake new file template and add processing of file without EOF.=)

With best regards. 

Sorry for my bad English, i am not native speaker.

**Comment by godvin** [comment]
I cloned repository of D-IDE and builded it. I could not repeat error at build version of D-IDE, error was fixed before, so i checked updates from GUI, but updates was not found. I launched D-IDE.Updater.exe and it updated D-IDE, error gone. I think need update installer and make update from GUI possible.

Sorry for the trouble, close issue please.

**Comment by aBothe** [comment]
Okay :)
